---
title: ""
format: gfm
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  out.width = "100%",
  eval = FALSE
)
```

## Install anyhoodle R package

```{r, eval = FALSE, `code-line-number` = 1}
devtools::install_git(
  url = "https://github.com/barnzilla/anyhoodle.git",
  force = TRUE
)
```

## Import dependencies

```{r, warning = FALSE, `code-line-number` = 1}
library(anyhoodle)
```

## Get descriptive stats and render bar plots

```{r, `code-line-number` = 1}
# Render bar plot of means for multiple numeric vectors
get_descriptives(
  df = mtcars,
  outcome_variable = c(mpg, disp, hp)
) %>%
render_bar_plot

# Render bar plot of means for multiple numeric vectors by a grouping variable
get_descriptives(
  df = mtcars %>%
    mutate(cyl = factor(cyl)),
  outcome_variable = c(mpg, disp),
  grouping_variable = cyl
) %>%
render_bar_plot

# Render bar plot of props for a non-numeric vector
get_descriptives(
  df = mtcars %>%
    mutate(cyl = factor(cyl)),
  outcome_variable = cyl
) %>%
render_bar_plot

# Render bar plot of props for multiple non-numeric vectors
get_descriptives(
  df = mtcars %>%
    mutate(
      cyl = factor(cyl),
      cyl2 = cyl
    ),
  outcome_variable = c(cyl, cyl2)
) %>%
render_bar_plot
```
